resources:
  repositories:
  - repository: templates
    type: github
    name: angerlynsjulceus/cicd_aws_s3
    endpoint: angerlynsjulceus

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: s3account_template.yml